### ISSUE TITLE
plugin manager

### ISSUE THREAD

**Issue by ghost** [KarateSnoopy/vcv-snoopy#5]
Hi! I m helping Andrew with the plugin manager

I tested your module today (installing) and it still shows the red dot after installing which means there is an error within your module.. I checked the json file and fixed a small error "version= "" " changed to "version=0.5.0" 

tried it again and the red dot still appears.. so i looked at your makefile here on github.. 
in there also the "VERSION=0.5.0" of your module is missing.. so if that is the same makefile you use to compile the lastest build then you need to change that in order to make work properly... take a look at the makefile from the tutorial ;)

**Comment by AndrewBelt** [comment]
Can confirm. I just removed Karate Snoopy from the Plugin Manager because it's one of the last remaining broken plugins.
Please make sure your Makefile looks like https://github.com/VCVRack/Tutorial/blob/master/Makefile, specifically that the VERSION is at the top of the file, above `include ../../plugin.mk`

**Comment by cschol** [comment]
This can be closed as we are working on integration with the plugin manager.
